# Conexión API extracción datos metereológicos

In [81]:
import pyowm
import json
import pandas as pd

from datetime import datetime

In [82]:
KEY = '16247b8439d1a62601d38844971ccccc'
owm = pyowm.OWM(KEY)
obs = owm.weather_at_place('Rafelguaraf, ES')

In [83]:
owm

In [84]:
owm.OWM_API_VERSION

'2.5'

In [85]:
columns = [
    "reception_time", "Location_name", "Location_lon", "Location_lat",
    "ID", "country",
    "reference_time", "sunset_time", "sunrise_time", "clouds", "rain",
    "wind_speed", "wind_deg", "humidity", "pressure", "sea_level", 
    "temp", "temp_kf", "temp_max", "temp_min", "status", "detailed_status", 
    "weather_code", "weather_icon_name", "visibility_distance", "dewpoint", 
    "humidex", "heat_index"
]
data_read = pd.DataFrame(columns=columns)

In [86]:
def get_data(obs):
    
    data = json.loads(obs.to_JSON())

    return {
    "reception_time" : datetime.fromtimestamp(data["reception_time"]),
    "Location_name" : data["Location"]["name"], 
    "Location_lon" : data["Location"]["coordinates"]["lon"], 
    "Location_lat" : data["Location"]["coordinates"]["lat"],
    "ID" : data["Location"]["ID"], 
    "country" : data["Location"]["country"],
        
    "reference_time" : datetime.fromtimestamp(data["Weather"]["reference_time"]),
    "sunset_time" : datetime.fromtimestamp(data["Weather"]["sunset_time"]),
    "sunrise_time" : datetime.fromtimestamp(data["Weather"]["sunrise_time"]),

    "clouds" : data["Weather"]["clouds"],
    "rain" : data["Weather"]["rain"],

    "wind_speed" : data["Weather"]["wind"]["speed"],
    "wind_deg" : data["Weather"]["wind"]["deg"],

    "humidity" : data["Weather"]["humidity"],

    "pressure" : data["Weather"]["pressure"]["press"],
    "sea_level" : data["Weather"]["pressure"]["sea_level"],

    "temp" : data["Weather"]["temperature"]["temp"],
    "temp_kf" : data["Weather"]["temperature"]["temp_kf"],
    "temp_max" : data["Weather"]["temperature"]["temp_max"],
    "temp_min" : data["Weather"]["temperature"]["temp_min"],

    "status" : data["Weather"]["status"],
    "detailed_status" : data["Weather"]["detailed_status"],
    "weather_code" : data["Weather"]["weather_code"],
    "weather_icon_name" : data["Weather"]["weather_icon_name"],

    "visibility_distance" : data["Weather"]["visibility_distance"],
    "dewpoint" : data["Weather"]["dewpoint"],
    "humidex" : data["Weather"]["humidex"],
    "heat_index" : data["Weather"]["heat_index"]
    }

In [87]:
data = get_data(obs)
data["reception_time"]

datetime.datetime(2020, 10, 5, 19, 7, 30)

In [95]:
[a for a, b in data]

ValueError: too many values to unpack (expected 2)

In [73]:
def database(obs, data_read):
    return data_read.append(pd.Series(get_data(obs)), ignore_index=True)

In [74]:
data_read = database(obs, data_read)
data_read.tail(5)

,reception_time,Location_name,Location_lon,Location_lat,ID,country,reference_time,sunset_time,sunrise_time,clouds,...,temp_max,temp_min,status,detailed_status,weather_code,weather_icon_name,visibility_distance,dewpoint,humidex,heat_index
1,2020-10-05 17:18:04,Rafelguaraf,-0.46,39.05,2512071,ES,2020-10-05 17:18:04,2020-10-05 19:38:21,2020-10-05 08:01:42,55,...,297.04,294.26,Clouds,broken clouds,803,04d,10000,None,None,None
2,2020-10-05 17:18:04,Rafelguaraf,-0.46,39.05,2512071,ES,2020-10-05 17:18:04,2020-10-05 19:38:21,2020-10-05 08:01:42,55,...,297.04,294.26,Clouds,broken clouds,803,04d,10000,None,None,None
3,2020-10-05 17:18:04,Rafelguaraf,-0.46,39.05,2512071,ES,2020-10-05 17:18:04,2020-10-05 19:38:21,2020-10-05 08:01:42,55,...,297.04,294.26,Clouds,broken clouds,803,04d,10000,None,None,None
4,2020-10-05 17:18:04,Rafelguaraf,-0.46,39.05,2512071,ES,2020-10-05 17:18:04,2020-10-05 19:38:21,2020-10-05 08:01:42,55,...,297.04,294.26,Clouds,broken clouds,803,04d,10000,None,None,None
5,2020-10-05 17:18:04,Rafelguaraf,-0.46,39.05,2512071,ES,2020-10-05 17:18:04,2020-10-05 19:38:21,2020-10-05 08:01:42,55,...,297.04,294.26,Clouds,broken clouds,803,04d,10000,None,None,None

In [65]:
data_read.head(1).T

                                       0
reception_time       2020-10-05 17:18:04
Location_name                Rafelguaraf
Location_lon                       -0.46
Location_lat                       39.05
ID                               2512071
country                               ES
reference_time       2020-10-05 17:18:04
sunset_time          2020-10-05 19:38:21
sunrise_time         2020-10-05 08:01:42
clouds                                55
rain                                  {}
wind_speed                          2.24
wind_deg                             260
humidity                              29
pressure                            1014
sea_level                           None
temp                              296.19
temp_kf                             None
temp_max                          297.04
temp_min                          294.26
status                            Clouds
detailed_status            broken clouds
weather_code                         803
weather_icon_name                    04d
visibility_distance                10000
dewpoint                            None
humidex                             None
heat_index                          None

In [41]:
data_read.columns.T

Index(['reception_time', 'Location_name', 'Location_lon', 'Location_lat', 'ID',
       'country', 'reference_time', 'sunset_time', 'sunrise_time', 'clouds',
       'rain', 'wind_speed', 'wind_deg', 'humidity', 'pressure', 'sea_level',
       'temp', 'temp_kf', 'temp_max', 'temp_min', 'status', 'detailed_status',
       'weather_code', 'weather_icon_name', 'visibility_distance', 'dewpoint',
       'humidex', 'heat_index'],
      dtype='object')

In [30]:
data_read.dtypes

reception_time         datetime64[ns]
Location_name                  object
Location_lon                  float64
Location_lat                  float64
ID                             object
country                        object
reference_time         datetime64[ns]
sunset_time            datetime64[ns]
sunrise_time           datetime64[ns]
clouds                         object
rain                           object
wind_speed                    float64
wind_deg                       object
humidity                       object
pressure                       object
sea_level                      object
temp                          float64
temp_kf                        object
temp_max                      float64
temp_min                      float64
status                         object
detailed_status                object
weather_code                   object
weather_icon_name              object
visibility_distance            object
dewpoint                       object
humidex                        object
heat_index                     object
dtype: object

In [97]:
d = pd.read_csv("../data/ListadoEStaciones_CSV_v04.csv", sep=";")

In [127]:
for i, row in d.iterrows():
    print(i, row["ID"])

0 8439X
1 8472A
2 8489X
3 8492X
4 8500A
5 8503Y
6 8520X
7 8523X
8 9563X
9 8354X
10 8368U
11 8376
12 8458X
13 8486X
14 9374X
15 9381I
16 9436X
17 9513X
18 9531Y
19 9546B
20 9550C
21 9561X
22 9569A
23 9573X
24 9935X
25 9998X
26 8058X
27 8058Y
28 8072Y
29 8193E
30 8203O
31 8270X
32 8283X
33 8290X
34 8293X
35 8300X
36 8309X
37 8319X
38 8325X
39 8337X
40 8381X
41 8395X
42 8409X
43 8414A
44 8416Y
45 8446Y
46 9562X
47 8005X

In [22]:
d.head(1).T

                                                                   0
ID                                                             8439X
NOMBRE                                                       Segorbe
MUNICIPIO                                                    Segorbe
PROVINCIA                                         Castelló/Castellón
ALTURA                                                           400
LATITUD                                                      394744N
º                                                                 39
'                                                                 47
"                                                                 44
Unnamed: 9                                                         N
GMS                                                        39°47'44"
GD (,)                                                   39,79555556
LATITUD GD                                               39,79555556
LONGITUD                                                     002907W
º.1                                                                0
'.1                                                               29
".1                                                                7
Unnamed: 17                                                        W
GMS.1                                                        0°29'7"
GD                                                       0,485277778
LONGITUD GD                                             -0,485277778
Latitud , Longitud               39,7955555555556,-0,485277777777778
Google maps         {Lat: 39,7955555555556,lng: -0,485277777777778},

In [19]:
d.columns

Index(['ID', 'NOMBRE', 'MUNICIPIO', 'PROVINCIA', 'ALTURA', 'LATITUD', 'º', ''',
       '"', 'Unnamed: 9', 'GMS', 'GD (,)', 'LATITUD GD', 'LONGITUD', 'º.1',
       ''.1', '".1', 'Unnamed: 17', 'GMS.1', 'GD ', 'LONGITUD GD',
       'Latitud , Longitud', 'Google maps'],
      dtype='object')

In [20]:
d.dtypes

ID                    object
NOMBRE                object
MUNICIPIO             object
PROVINCIA             object
ALTURA                 int64
LATITUD               object
º                      int64
'                      int64
"                      int64
Unnamed: 9            object
GMS                   object
GD (,)                object
LATITUD GD            object
LONGITUD              object
º.1                    int64
'.1                    int64
".1                    int64
Unnamed: 17           object
GMS.1                 object
GD                    object
LONGITUD GD           object
Latitud , Longitud    object
Google maps           object
dtype: object